apiVersion: v1
enabled: true
name: gradient-ai/stable-diffusion-webui
image: ghcr.io/gradient-ai/stable-diffusion-webui:latest
healthChecks:
  readiness:
    path: /
resources:
  ports: [7860]
  replicas: 1
  machineType: V100
  autoscaling:
    enabled: true
    maxReplicas: 2
    metrics:
      - metric: requestDuration
        summary: average
        value: 0.15
      - metric: cpu
        summary: average
        value: 30
      - metric: memory
        summary: average
        value: 45
integrations:
  - type: git-lfs
    name: sd15
    url: https://huggingface.co/runwayml/stable-diffusion-v1-5
  - type: git-lfs
    name: falcon-40b-instruct
    url: https://huggingface.co/tiiuae/falcon-40b
